version: '2.7'
services:
  redpanda:
    image: vectorized/redpanda:v21.4.3
    ports:
      - "9092:9092"
      - "8081:8081"
      - "9644:9644"
    volumes:
      - ./redpanda/data:/var/lib/redpanda/data
      - ./redpanda/logs:/var/lib/redpanda/logs
    command: redpanda start

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "trading_topic:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  main:
    build:
      context: .
    depends_on:
      - kafka
      - redpanda
